### ISSUE TITLE
nvim markdown folding

### ISSUE THREAD

**Issue by hjdivad** [hjdivad/dotfiles#9]
cf 
- https://github.com/nelstrom/vim-markdown-folding/
- https://github.com/plasticboy/vim-markdown

**Comment by hjdivad** [comment]
nelctrom/vim-markdown-folding is slow on vim but works

on neovim it creates folds but does not seem to nest them

**Comment by hjdivad** [comment]
nevermind was missing config; still maybe compare against `plasticboy/vim-markdown`

**Comment by RolandWarburton** [comment]
Hey I am looking to do markdown folding in my own neovim config.

Can you include the config that you used to get folding working if you still have it around?
